# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JinUS8GrEwD6zA_DANrJfnIjma19b1C6

a) Implémentation de la fonction polynomiale
"""

def Polynome(x):
  a= (x**3)-1.5*(x*x) -(6*x) +5
  return a

Polynome(5)

"""Implémenter la fonction factorielle : Approche classique :"""

def fact(x):
  if x == 0:
    return 1
  else:
    y=1
    for z in range(2,x+1):
      y = y * z
    return y

fact(5)

"""Implémenter la suite de Fibonnaci"""

def fibonacci(n):
    if(n == 0):
        return 0
    elif n == 1:
      return 1
    else:
        return (fibonacci(n-1) + fibonacci(n-2))
n = int(input("Entrez le nombre de termes:"))

for i in range(n):
  print(fibonacci(i))

fibonacci(6)