# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gv2d-fPPyuvnkvDWnE-niQnoCMpAdtST

Création de fonction comportant des modules de gestions des
exceptions
"""

def factorielle(x):
  if type(x) == str :
    print("Saisie d'une str dans les arguments de la fonction. Entrez des valeurs entieres")
  if type(x) == complex:
    print("Saisie d'un nombre complexe. Entrez des valeurs entieres")
  if x < 0 :
    print("Saisie d'un nombre négatif. Entrez des valeurs entieres")
  if x > 10**20 :
    print("Saisie d'un tres grand nombre. Entrez des valeurs entieres")
  if x < 10:
    print("Saisie d'un tres petit nombre. Entrez des valeurs entieres")
  if x == 0:
    return 1
  else:
    y=1
    for z in range(2,x+1):
      y = y * z
    return y